### ISSUE TITLE
Proposal: Re-license repo, Move theia-ide web site to eclipse-theia

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-website#122]
Moving the web site sources to the eclipse-theia org can potentially increase visibility and also welcome additional contributions and contributors. In particular it puts contribuions under the same ECA as other core repos.
As websites IMHO do not do releases, nor usually requires CQs, I believe the overhead should be minimal.

@marcdumais-work @svenefftinge

**Comment by marcdumais-work** [comment]
Yes, I think that would make sense. A nice side-effect would be that write access to the repo would be automatically managed by the foundation - ATM I believe that many committers would not have access, specially those who joined after we moved to the Foundation. 

I just noticed the repo has no stated license. I wonder if that would be a problem. I do not think I know all the contributors who have commits in the repo.

**Comment by svenefftinge** [comment]
Sounds good to me!

**Comment by marcdumais-work** [comment]
Sharon has confirmed we'll need to re-licence this repo, before we can move it to the Foundation, under the Eclipse Theia project and GH org. It will be the same for the other two repos we want to do the same with. 

Ref:
- https://github.com/theia-ide/generator-theia-extension/issues/60
- https://github.com/theia-ide/vscode-builtin-extensions/issues/16

**Comment by marcdumais-work** [comment]
Hi @nisarhassan12 ,

For the purpose of re-licensing this repo so we can move it under the Eclipse Foundation, we'll need to confirm your contributor's status. 

Do you own your contributions to this repo or were they made on the behalf of someone else, who would own them? I think I have in mind you may be (or have been at the time of the contributions) working for TypeFox? Can you confirm who owns your contributions to this repo? 

cc: @svenefftinge

**Comment by nisarhassan12** [comment]
Hi. @marcdumais-work 

I made those contributions on behalf of TypeFox. I still work for them.

**Comment by JonasHelming** [comment]
see https://github.com/theia-ide/theia-website/wiki/Re-licensing-theia-ide-theia-website

Update: all individual contributors have been contacted, we got permission already from:
alainbernard
Stefano Populin

For tstibbs, see https://github.com/theia-ide/theia-website/issues/127

**Comment by JonasHelming** [comment]
@marcdumais-work : All individuals agreed already, I have updated the wiki.

**Comment by JonasHelming** [comment]
@marcdumais-work Is the permission from Red Hat still pending? Maybe we should trigger this again?

**Comment by marcdumais-work** [comment]
Triggered again: https://github.com/eclipse-theia/generator-theia-extension/issues/60#issuecomment-764902587

**Comment by JonasHelming** [comment]
@marcdumais-work I guess we can close this, correct?

**Comment by marcdumais-work** [comment]
Yes, thanks for the reminder Jonas.
