### ISSUE TITLE
Add documentation how to package Theia

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-website#131]
We would like to contribute documentation how to package Theia as Desktop app and how to create installers/packages for Windows, MacOS and Linux. The documentation will be centered around a Theia blueprint product that can be used as a template. This effort is currently on the way in the [Theia Example Repo](https://github.com/eclipse-theia/theia-example) and is also summarized in [this issue](https://github.com/eclipse-theia/theia/issues/8707).
We propose to add the documentation on the [Theia documentation page](https://theia-ide.org/docs/) with the title "Packaging Theia" in the section "Using Theia" below the item "Building your own IDE". 
Please let us know what you think.

**Comment by koegel** [comment]
@marcdumais-work What do you think?

**Comment by koegel** [comment]
@marcdumais-work Could you maybe ask someone on the team to review this PR. This is about adding the documentation on customizing the blueprint as discussed earlier today. Thanks!

**Comment by brianking** [comment]
For this issue and #134, I'm following along with the PR in #133. Because it is such a moving target I don't think @croundy and I will be able to do our copy review until this is checked in. I find it difficult to add word or sentence suggestions as review comments here.

Can it be checked into a staging area from where we can then grab the raw text and submit a PR before it is changed again?

**Comment by koegel** [comment]
I would propose you directly suggest changes on the PR. To do so go to the PR's file view:
https://github.com/eclipse-theia/theia-website/pull/133/files
You can start a review there and comment on particular lines or even better suggest changes directly, for details see:
https://haacked.com/archive/2019/06/03/suggested-changes/
For a preview you can also open the files from the file view:
![image](https://user-images.githubusercontent.com/1044916/107375401-ff1d4f80-6ae8-11eb-9769-bb2057478d87.png)
This will provide you with a preview like here:
https://github.com/eclipse-theia/theia-website/blob/664c1985fc2bbcb2494bf208611808911d6ca53d/src/docs/blueprint_documentation.md

IMHO this is the best way to go, since it makes sure you see review the latest state and it keeps overhead at a minimum.
