### ISSUE TITLE
Add blueprint download page

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-website#134]
We need to add a page for explaining what the blueprint is and listing the download options for it (also see https://github.com/eclipse-theia/theia-example/issues). 
We should link this page also from the landing page and a button right to the "Try in Gitpot" button:
![image](https://user-images.githubusercontent.com/1044916/106452090-b382fa00-6487-11eb-8c30-488efaaf2e11.png)

**Comment by koegel** [comment]
The text we propose for the button is "Try on Desktop", alternatively we could also label it with "Download Blueprint". Feedback welcome. @jonashelming @vince-fugnitto What do you think?

**Comment by JonasHelming** [comment]
I like "try on desktop" or just "download"

**Comment by JonasHelming** [comment]
However, "download blueprint" also sounds good to me, sorry, I basically like all the options :-)

**Comment by vince-fugnitto** [comment]
> The text we propose for the button is "Try on Desktop", alternatively we could also label it with "Download Blueprint". Feedback welcome. @JonasHelming @vince-fugnitto What do you think?

I'd be fine with both, or something more explicit like "Try Theia Blueprint" (whatever is best to convey it's an example product which can be used as a template). 

Will the link point to the `blueprint` docs with links, or will it point straight to the downloads?

**Comment by koegel** [comment]
> Will the link point to the `blueprint` docs with links, or will it point straight to the downloads?

It will link directly to the download page, which begins with an explanation of what it is:

### What is this?
Eclipse Theia Blueprint product is a template to showcase the capabilities of Theia as well as how to build desktop-based products based on the platform. Theia Blueprint assembles a selected subset of existing Theia features and extensions. We provide installers for Theia Blueprint to be downloaded (see below) as well as documentation on how to customize this template to build a product and installers for your own Theia-based product.

### What is it not?
Eclipse Theia Blueprint product is not a production-ready product. Therefore, it is also not a replacement for Visual Studio Code or any other IDE.
