### ISSUE TITLE
Broken link on authoring extensions

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-website#144]
https://theia-ide.org/docs/authoring_extensions/
Link to dependency injection is broken

**Comment by vince-fugnitto** [comment]
@JonasHelming there are a few that are broken:
- https://github.com/eclipse-theia/theia-website/issues/129
- https://github.com/eclipse-theia/theia-website/issues/65

**Comment by JonasHelming** [comment]
#129 I actually don't know where to link to, the other ones I fixed in the PR
