### ISSUE TITLE
Try in Gitpod button on Website links to Gitpod VS Code announcement

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-website#148]
While creating the Theia Blueprint article for the EF April newsletter I noticed that the "Try in Gitpod" button on https://theia-ide.org/ prompts new users with this message:
![image](https://user-images.githubusercontent.com/1044916/115043105-6b934100-9ed4-11eb-9679-7644cd6dc7e0.png) 

Since the button is shown very prominently on the Theia landing page and promises to let me try Theia in Github this is rather unexpected. What do you think, @marcdumais-work, @svenefftinge, @vince-fugnitto ? 
Can we maybe add a different button like "Try in OpenShift" as an alternative? This topic is rather urgent since the newsletter will be published next week imho and will hopefully attract visitors to the Theia webpage.

**Comment by vince-fugnitto** [comment]
@koegel the button will start the `example-browser` application from gitpod (gitpod itself is not the "try").

https://gitpod.io/#github.com/eclipse-theia/theia

For users who are logged into gitpod, this will start the application, and they can open it with the "open browser" notification:

![image](https://user-images.githubusercontent.com/40359487/115045797-d7f64c00-9ea4-11eb-9f5d-a51f5dda0901.png)

**Comment by koegel** [comment]
New users are seeing the prompt that I posted above which basically gives me the impression that I am not trying Theia but Visual Studio Code. The user's that we try to address with the April newsletter (as any new users) will very likely see the message. So my concern is not that they can try Theia within Gitpod but that it seems to them that they try VS Code.

**Comment by brianking** [comment]
This has already been flagged at https://github.com/eclipse-theia/theia/discussions/9301. 

We need to consider:

a) In the short-term if we should remove that button from the website 

b) in the long-term, options to replace it, i.e. find a hosted solution when Theia is integrated

**Comment by koegel** [comment]
> This has already been flagged at [eclipse-theia/theia#9301](https://github.com/eclipse-theia/theia/discussions/9301).
> We need to consider:
> a) In the short-term if we should remove that button from the website
> b) in the long-term, options to replace it, i.e. find a hosted solution when Theia is integrated
I agree with @brianking, we should consider removing the button in the short term to avoid any confusion for new users. I could ask @jfaltermeier to do so if we reach consensus. The April newsletter is released mid next week as far as I know so we need to move quickly imho. @svenefftinge, @marcdumais-work, @vince-fugnitto Any more thoughts on this?

**Comment by azatsarynnyy** [comment]
> Can we maybe add a different button like "Try in OpenShift" as an alternative?

In such case, we can use the following link https://workspaces.openshift.com/f?url=https://github.com/eclipse-theia/theia
It requires a registration on https://developers.redhat.com/developer-sandbox

**Comment by sunix** [comment]
> > Can we maybe add a different button like "Try in OpenShift" as an alternative?
> 
> In such case, we can use the following link https://workspaces.openshift.com/f?url=https://github.com/eclipse-theia/theia
> It requires a registration on https://developers.redhat.com/developer-sandbox

+1 for that: it is free to try and 100% opensource; ideal to see how Eclipse Theia could be customized and used in an Enterprise ready cloud solution.

We could also mention the GKE integration with screen shots etc.

**Comment by koegel** [comment]
@spoenemann the newsletter will go out tomorrow probably, so unless I hear otherwise, we would temporarily remove the button for now. Any other ideas?

**Comment by brianking** [comment]
I talked briefly with @svenefftinge late last week about this and we concluded that given the current CTA on the button, it is a good idea to remove it. 

We could consider offering Gitpod as an option to hack on Theia, but that is a different discussion / issue.

**Comment by koegel** [comment]
> I talked briefly with @svenefftinge late last week about this and we concluded that given the current CTA on the button, it is a good idea to remove it.
> 
> We could consider offering Gitpod as an option to hack on Theia, but that is a different discussion / issue.

OK, thanks, @jfaltermeier has already prepared a [PR](https://github.com/eclipse-theia/theia-website/pull/151) (thanks!). 
@vince-fugnitto @marcdumais-work @spoenemann @JonasHelming Can anyone of you please r[eview and merge the PR](https://github.com/eclipse-theia/theia-website/pull/151) as soon as possible, ideally by end of this day. Thank you!

**Comment by koegel** [comment]
Thank you, @jfaltermeier!

**Comment by koegel** [comment]
For re-adding a button I opened #152
