### ISSUE TITLE
Re-add a button on landing page to "Try in the cloud"

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-website#152]
It would be good to have a quick way to try Theia directly hosted in the cloud and add this as a button on the landing page, similar to what was there before #148. [One idea was to add a link to Theia running in OpenShift](https://github.com/eclipse-theia/theia-website/issues/148#issuecomment-823373640).

When adding another button to the landing page again, we should rename the existing button from "Try now" to something like "Try on desktop" or imho even better create a "Try now" landing page where you get more options to try Theia.

**Comment by koegel** [comment]
It would be good to have a quick way to try Theia directly hosted in the cloud and add this as a button on the landing page, similar to what was there before #148. [One idea was to add a link to Theia running in OpenShift](https://github.com/eclipse-theia/theia-website/issues/148#issuecomment-823373640).

**Comment by l0rd** [comment]
cc @azatsarynnyy @benoitf

**Comment by azatsarynnyy** [comment]
Thanks @l0rd!
My proposal for Developer Sandbox is still relevant. See https://github.com/eclipse-theia/theia-website/issues/148#issuecomment-823373640

**Comment by benoitf** [comment]
@azatsarynnyy you may file a PR proposing that ?

**Comment by koegel** [comment]
I think it would be best to create a landing page where the button "Try now" goes to. On this page we could list different options how you can directly try Theia:

- Desktop => Links to Theia Blueprint Desktop App Download
- Browser => Links to Theia Blueprint Docker Container (not yet available but planned)
- Cloud
   - [Red Hat Codeready Workspaces](https://developers.redhat.com/products/codeready-workspaces/overview) based on [Eclipse Che](https://www.eclipse.org/che/getting-started/cloud/)
   - [Coffee editor demo](https://eclipsesource.com/coffee-editor) based on [Eclipse EMF.cloud](https://www.eclipse.org/emfcloud/)
   - [Google Cloud Shell Editor](https://cloud.google.com/blog/products/application-development/introducing-cloud-shell-editor)

**Comment by marcdumais-work** [comment]
@koegel I'm not sure about the proposal. At least in my mind, there are two aspects that are mixed-together, that might best remain split:

1) "Try Theia Now": link to a _workspace server_ service, to open the the main repo's example browser application, built from the master branch (or potentially another branch or commit) and let one play with the resulting example application and browse the app's and repo's source code. 
    - For this one I think it's only a "nice to have", that the application be Theia-based, but I believe the most important aspect is that it be super easy and quick to proceed, to try the link/service. E.g. ideally no sign-up or associated fees. If there must be a sign-up, let it be one that's widely adopted already, like GitHub.
2) Showcase and give an opportunity to try various Theia-based applications: a very useful page to have, that shows the diversity of results, that can be achieved with the framework. 
    - Obviously an application needs to be Theia-based to be interesting here.

**Comment by marcdumais-work** [comment]
I guess for 1), we could have more than one link, but the top one should be the easiest to try, IMHO.

**Comment by brianking** [comment]
@marcdumais-work I would disagree, at least based on my understand of "Try". 'Try Theia Now' to me means try an application/service that uses Theia, and not 'try hacking on Theia'.

Everything else I agree with.

**Comment by koegel** [comment]
> @koegel I'm not sure about the proposal. At least in my mind, there are two aspects that are mixed-together, that might best remain split:
> 
> 1. "Try Theia Now": link to a _workspace server_ service, to open the the main repo's example browser application, built from the master branch (or potentially another branch or commit) and let one play with the resulting example application and browse the app's and repo's source code.
>    
>    * For this one I think it's only a "nice to have", that the application be Theia-based, but I believe the most important aspect is that it be super easy and quick to proceed, to try the link/service. E.g. ideally no sign-up / sign-on, or associated fees. If there must be a sign-on, let it be one that's widely adopted already, like GitHub.
> 2. Showcase and give an opportunity to try various Theia-based applications: a very useful page to have, that shows the diversity of results, that can be achieved with the framework.
>    
>    * Obviously an application needs to be Theia-based to be interesting here.

@marcdumais-work You are probably right that the "Try now" landing page mixes up two things, but I think it is two different things than what you have in mind :):
1. Try now: Giving the viewer a possibility to try Theia right away, ideally with as few steps as possible (e.g. no built, no new account etc). In this regard I also agree with what @brianking says about the expectation of a "Try now" button. I would expect to get to an application right away that demos the power of the platform to me, like Theia Blueprint. 
2. See other adopters/products build on Theia: This is more to see different examples how Theia-based products can look like and to demonstrate its wide-spread adoption. It is probably a product-centric version of the adopters page. For this usecase it is not so important for each option to be approachable very easily, some might require creating accounts, etc.

For option 1: I think it would be best to have a button that directly takes me to a cloud-hosted Theia Blueprint version with little to no user interaction required. Potentially there would be a second button "Try on your machine", then the first button would maybe be relabeled to "Try in the cloud". 
@azatsarynnyy: Any chance to have a developer sandbox that does not require a login to be created?
@spoenemann: Any ideas on how we could use Gitpod for this but without the VS Code prompt? Are you planning to maintain a Theia offering on Gitpod?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy: Any chance to have a developer sandbox that does not require a login to be created?

Hi @koegel, unfortunately, we can't provide such access to DevSandbox, without requiring a login via Red Hat Single Sign-On.

**Comment by spoenemann** [comment]
> @spoenemann: Any ideas on how we could use Gitpod for this but without the VS Code prompt? Are you planning to maintain a Theia offering on Gitpod?

FYI Gitpod is now separated from TypeFox, so I cannot say anything about that. @svenefftinge might answer.

**Comment by jfaltermeier** [comment]
Closed with #304
