### ISSUE TITLE
[content] Footer Update

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-website#158]
Update the footer to a) reflect the site better, b) surface up other external content better, c) bring in line with other Eclipse properties.

The Che site footer might be a good model to follow but we don't need to follow it exactly.

<img width="934" alt="Screenshot 2021-05-05 at 17 57 52" src="https://user-images.githubusercontent.com/114116/117179818-72beb800-adcb-11eb-9f0e-e3652761a0dc.png">

**Comment by JonasHelming** [comment]
The "about" link was already added, the attribution was corrected. I am actually happy with the current footer, the Che footer seems a little bit two much. @brianking : Do you have any specific link you are missing? Can we close this?

**Comment by brianking** [comment]
I'm ok with how it is now.
