### ISSUE TITLE
[content] Adopters - Product Screenshots

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-website#160]
Add product screenshots to be used in features on the website.

Start with ones in this post. Permissions will need to be given by the companies.
https://blogs.eclipse.org/post/brian-king/eclipse-theia-builds-momentum

**Comment by JonasHelming** [comment]
The goal is to show visitor immediately and visually three core messages:

1. Theia is a platform for building tools
2. The advantages listed below the gallery (should be moved up)
3. Theia is adopted by quite a few companies and products

**Comment by JonasHelming** [comment]
@brianking : Could you check for permission on the other, missing screenshots in the blog post?
