### ISSUE TITLE
Theia Logo Alignment in Theia vs Vs Code section

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-website#168]
@JonasHelming @max-elia Liking the changes so far, thanks.

In the Theia vs VS Code section (if we are keeping it) the Theia logo needs to align on the left with the other content on the page. Right now it overflows to the edge of the page.

<img width="837" alt="Screenshot 2021-06-09 at 11 39 23" src="https://user-images.githubusercontent.com/114116/121340699-cc108e80-c917-11eb-9f38-7b387b432913.png">

_Originally posted by @brianking in https://github.com/eclipse-theia/theia-website/issues/154#issuecomment-857588899_

**Comment by JonasHelming** [comment]
@brianking : I am not really sure whether I understand this issue. The screenshot does not show any "misalignment". Could you provide more details, please?

**Comment by brianking** [comment]
I am not able to reproduce anymore. This can be closed.
