### ISSUE TITLE
[content] Resource Section / Page

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-website#182]
An idea from @tsmaeder that came out of the Theia Dev Meeting today was to have a section on the site to list content, e.g. articles, related to Theia. 

The first thing to be decided should be whether this will be a section to an existing (or proposed) page, or whether to create a new page and fill it out with other content. If new, an example is a page called 'Resources' that would have other sections like video, social content, and more.

/cc @JonasHelming

**Comment by JonasHelming** [comment]
Maybe we open a sub page in the documentation for this? Or do you envision this to be in the main navigation?

**Comment by brianking** [comment]
In documentation doesn't feel right to me, as these are more marketing resources (though some things could overlap, e.g. a specific video tutorial). 

I'm not sure the right menu item/label for it. We could follow the model of what ecdtools.eclipse.org is doing and have a Resources menu with sub-items like Community, Events, and Resources. The latter could be the page being proposed here.

**Comment by JonasHelming** [comment]
I think "community" does not really fit under resources. So we should make resources a top level category then. Maybe we can removed "features"?

**Comment by tsmaeder** [comment]
I would simply add a "news" heading to the main menu. There is room IMO and we can rethink the navigation structure some other time.

**Comment by brianking** [comment]
> I would simply add a "news" heading to the main menu. There is room IMO and we can rethink the navigation structure some other time.

I'm not convinced a whole page is needed just for some links to news articles. Do you have any good examples of that?

**Comment by JonasHelming** [comment]
fixed by #278
