### ISSUE TITLE
Add theiaCon talks

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-website#237]
As suggested by Matthew (https://twitter.com/DavisTurlis/status/1461032412268355589) we might want to put the recordings of some of the generic Theia talks from TheiaCon on the Theia website, e.g. the adopter introduction and the "why Theia" talk by @marcdumais-work

**Comment by JonasHelming** [comment]
Proposal:

Under the section "Contributors & Adopters", we add a new section: "Introductions to Eclipse Theia"
There we show the three talks using a format similar to the following screenshot

![image](https://user-images.githubusercontent.com/1052615/143606416-a49e57c4-2bc9-40b3-979e-341fcaf4d838.png)

Pictures can be found here: https://events.eclipse.org/2021/theiacon/

Instead of the big names, we use the talk titles, so e.g. we replace "Jonas Helming" with "How to be an Eclipse Theia Adopter"

In the text below we add the name and project lead, such as:

"Jonas Helming, Theia project lead and Software Engineer at EclipseSource"

The picture and the name of the talk link to youtube.

Talks:

Why Eclipse Theia - Marc Dumais
https://youtu.be/xs0haWTulrY

How to be an Eclipse Theia Adopter - Jonas Helming
https://youtu.be/SPO8pudgJak

The Eclipse Theia Architecture - Thomas Mäder
https://youtu.be/KN2JUsFuEhU

**Comment by brianking** [comment]
Alternative proposal:
Add a new 'Resources' page and embed the videos there for easier consumption.

**Comment by JonasHelming** [comment]
I believe embedding videos is problematic without an explicit mention in the private policy even when using the no cookie version. I like the idea of a resource page, but let's handle this idea separately, please open a follow up.

**Comment by marcdumais-work** [comment]
@JonasHelming good initiative! The proposal LGTM!
