### ISSUE TITLE
Theia down

### ISSUE THREAD

**Issue by ggodlewski** [eclipse-theia/theia-website#254]
The website https://theia-ide.org/ seems to be down
Docker images from https://github.com/theia-ide/theia-apps#theia-docker are not available.

I discovered this project today and so far I'm not able to use it.
Did it move somewhere?

**Comment by vince-fugnitto** [comment]
> The website https://theia-ide.org/ seems to be down Docker images from https://github.com/theia-ide/theia-apps#theia-docker are not available.

@ggodlewski thank you for the issue :+1: 

The website is currently down as it is being moved under the eclipse foundation, there is a [ticket](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/778).

The docker images are no longer being published on dockerhub, please see: https://github.com/theia-ide/theia-apps/issues/496.

**Comment by vince-fugnitto** [comment]
@ggodlewski until the website is back up, you can refer to the following [link](https://deploy-preview-253--romantic-mcclintock-8d974f.netlify.app/) for the time being. From the documentation you can see how to build your own application based on the theia framework ([doc](https://deploy-preview-253--romantic-mcclintock-8d974f.netlify.app/docs/composing_applications/)).

As a replacement to the images present in `theia-apps` you can try the ones published by IBM as a replacement:
- https://quay.io/repository/zowe-explorer/theia?tab=tags
