### ISSUE TITLE
update plugin typedoc link

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-website#273]
**Description**

The following [link](https://github.com/eclipse-theia/theia-website/blame/master/src/docs/authoring_plugins.md#L197) should be updated to: https://eclipse-theia.github.io/theia/docs/next/modules/plugin.html

**Additional Info**

- https://github.com/eclipse-theia/theia-website/issues/129#issuecomment-1053609848

**Comment by ucg8j** [comment]
Hey @vince-fugnitto - sorry for the delay. Raised [a PR ](https://github.com/eclipse-theia/theia-website/pull/301). Do you have any guidance on the failing CI check

> eclipsefdn/eca — The author(s) of the pull request is not covered by necessary legal agreements in order to proceed.

**Comment by vince-fugnitto** [comment]
@ucg8j no problem, and the eca needs to be signed, similarly to how it’s documented here (https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement). The authorship and eca emails should match to succeed 👍

**Comment by ucg8j** [comment]
@vince-fugnitto thanks for the link. I've
- created an Eclipse Foundation account
-  signed Eclipse Contributor Agreement (ECA) on file.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/6220504/168483542-615da84c-7be6-4a98-bd96-c73ecbda8854.png">
with the following email
<img width="214" alt="image" src="https://user-images.githubusercontent.com/6220504/168483566-371ab8ee-4a92-4a51-98a9-e0ae3c763d0b.png">
- amended my previous commit message to include the signed off by line
<img width="412" alt="image" src="https://user-images.githubusercontent.com/6220504/168483644-511b1195-d258-4283-87cc-be73f021eaee.png">
- re-triggered the validation a few times

Not sure where I'm going wrong here. Any pointers?
