### ISSUE TITLE
Blogs page is empty in Firefox

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia-website#285]
https://theia-ide.org/blogs/ shows no blog post entries in Firefox, but it does in Chromium.

**Comment by JonasHelming** [comment]
@max-elia : Do you an idea?

**Comment by tsmaeder** [comment]
The log says: 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://planeteclipse.org/planet/ecdtools.xml. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 405.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://planeteclipse.org/planet/ecdtools.xml. (Reason: CORS request did not succeed). Status code: (null).
Uncaught TypeError: NetworkError when attempting to fetch resource. Blogs.js:102:21
    d Blogs.js:102
    maybePromisify utils.js:98

**Comment by max-elia** [comment]
I changed the parseURL method used by the library to the browsers native fetch method. It should now be working also on Firefox.
