### ISSUE TITLE
Smartface missing from adopters list

### ISSUE THREAD

**Issue by autumnfound** [eclipse-theia/theia-website#324]
Looking into the site, it looks like a new adopter is missing from the adopters' list on the homepage. It is available from our API which I'm assuming is the source of the magic. From what I can tell, this is read in by some page context, so I made sure my cache was clean before trying again and still couldn't see it. Is this only gathered at build time?

**Comment by JonasHelming** [comment]
Which new adopter?

**Comment by autumnfound** [comment]
Smartface https://gitlab.eclipse.org/eclipsefdn/it/api/eclipsefdn-project-adopters/-/issues/187

**Comment by JonasHelming** [comment]
I see. Thank you for the report. The build needs to run to grap the API. I see they also added a screneshot. Do you want to add a PR on this repo to add the screenshot in the slider? This would automatically also add them to the list (you can check on the PR)

**Comment by furkanarabaci** [comment]
@autumnfound @JonasHelming Hello, I am from Smartface. I've checked the codebase and it looks like I can add Smartface as adopters. 

However, it looks like the GIF we've provided doesn't have similar/exact aspect ratio with other adopters screenshot, so I am going to re-record the gif for better outlook.

**Comment by JonasHelming** [comment]
Sounds great! Just to be sure, your logo will already appear in the list of adopters after the next rebuild. So you just need to add the screenshot of the tool to the slider.

**Comment by smartface-team** [comment]
@JonasHelming Sorry for the delay, successfully created PR and Contribution Agreement is also done as well.
