### ISSUE TITLE
composing-applications: reference `latest` over `next`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-website#403]
**Description**

The [Build your own IDE/Tool](https://theia-ide.org/docs/composing_applications/) documentation references the `next` version of Theia dependencies which can be error prone, and result in a mismatch of extensions if a publish failed. Given these reasons downstream extenders should more likely use `latest` which is properly published as is the basis for releases.

The fix would be to replace uses of `next` with `latest` in the documentation:

https://github.com/eclipse-theia/theia-website/blob/231c243fce89813d2214ebd7ff496e67bf543563/src/docs/composing_applications.md?plain=1#L30-L50

https://github.com/eclipse-theia/theia-website/blob/231c243fce89813d2214ebd7ff496e67bf543563/src/docs/composing_applications.md?plain=1#L73-L113

**Comment by JonasHelming** [comment]
@vince-fugnitto Do you have a fix ready? I also made a note to fix this...

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Do you have a fix ready? I also made a note to fix this...

@FernandoAscencio is planning on working on a quick fix.
