### ISSUE TITLE
Sign up not working on Theia Community website

### ISSUE THREAD

**Issue by umar-shabbir** [eclipse-theia/theia-website#474]
I tried sign up on [Theia Community](https://community.theia-ide.org/) and after filling the required fields, clicking the "Create your account" button results in following error message appearing on the sign up form:
**"Incorrect username, email or password"**
Before clicking on create your account, I verified that all the input is correct and it does display following messages to indicate the correct input:
- We will email you to confirm
- Your username is available
- Your password looks good.

**Comment by JonasHelming** [comment]
Hi,
I just tested this, it works fine for me. Please note that we are relying on discourse here.
Could you maybe try this again, please?

**Comment by umar-shabbir** [comment]
Hi,
I signed up using Github at that time and that worked fine.
And yes, now I just tested the sign up form again and it is working. Could be some temporary issue when I tried earlier.
Thanks
