### ISSUE TITLE
proposal: extract `release announcements` to their own page

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-website#479]
**Description**

The website currently lists `release announcements` under `resources > other resources` which makes links, tutorials, and other useful resources as hard to find for newcomers. The `release announcements` section will only grow with each release and it would be better for them to be under their own page.

**Proposal**

Place `release announcements` under a new page `resources >  release announcements`.

cc @JonasHelming any thoughts?

**Comment by JonasHelming** [comment]
Yes, i think that make sense. I would probably move them to a section on the existin release page under the community releases and link them in the header of this page. If this makes sense to you, I will prepare the change

**Comment by vince-fugnitto** [comment]
Sounds good to me!
