### ISSUE TITLE
Getting Started Docs - Broken Link - " used as a template "

### ISSUE THREAD

**Issue by landmaxcanada** [eclipse-theia/theia-website#522]
The Theia IDE can also be [used as a template](http://localhost:8000/docs/blueprint_documentation/) to get started with building your own tool. Please have a look at the project goals for more details!

http://localhost:8000/docs/blueprint_documentation/ is incorrect.

**Comment by msujew** [comment]
Probably a copy and paste error during https://github.com/eclipse-theia/theia-website/pull/470. Should've been `https://theia-ide.org/docs/blueprint_documentation/` instead.

**Comment by JonasHelming** [comment]
@landmaxcanada Thank you very much for the report, PR is opened.

**Comment by JonasHelming** [comment]
closed by #525
