### ISSUE TITLE
How to update adopter logo? 😉 

### ISSUE THREAD

**Issue by inlann** [eclipse-theia/theia-website#531]
Hello,

Glad to share our new logo with Theia 😉 

How can I update it to the Theia website?

Really appreciate!

**Comment by JonasHelming** [comment]
Hi,

sounds great. It would be the same process as adding it. Simplest way is to open an issue as describe here in Option 1:
https://ecdtools.eclipse.org/adopters/get-listed/

**Comment by inlann** [comment]
Hello,

Glad to know that our new logo has been accepted by Eclipse. But there is a little bug 😂 :

The link of the logo is a svg image on https://api.eclipse.org/adopters/ : 

https://api.eclipse.org/adopters/assets/images/adopters/logo-terapines.svg

![image](https://github.com/eclipse-theia/theia-website/assets/33852855/1fddda30-45e3-449e-93b0-ae03172a3205)

But the link on Theia website is a png image:
https://api.eclipse.org/adopters/assets/images/adopters/logo-terapines.png

![image](https://github.com/eclipse-theia/theia-website/assets/33852855/8b235748-d8df-4e94-a6aa-c59f4f32054d)

Should I upload the logo with png format?

**Comment by inlann** [comment]
@JonasHelming Really appreciate ;)

**Comment by JonasHelming** [comment]
Should be fixed now, please check https://theia-ide.org/
