### ISSUE TITLE
docs: describe that applicationName is nested

### ISSUE THREAD

**Issue by srl295** [eclipse-theia/theia-website#612]
https://theia-ide.org/docs/blueprint_documentation/#customizing-the-app says:

> The application name can be adapted in applications/electron/package.json: Open the file and adapt the value of property theia.frontend.config.applicationName to the desired name.

When using the yo generator, I edited `electron-app/package.json` and updated:

```json
{
  "theia": {
    "frontend": {
        "applicationName": "myapp"
    }
  }
}
```

At first I had just added `theia.frontend.config.applicationName` literally (one key rather than nested) but that didn't work. Then, I noticed the "theia" key was there and already had content in it.

**Comment by JonasHelming** [comment]
Would adding this link help? https://github.com/eclipse-theia/theia-blueprint/blob/ed203687bad53fdbd22012926978ac40d7d8cd23/applications/electron/package.json#L26

**Comment by srl295** [comment]
@JonasHelming that would make a good example.

**Comment by JonasHelming** [comment]
see https://eclipse-theia.github.io/theia-website-previews/pr-previews/pr-613/docs/blueprint_documentation#branding
