### ISSUE TITLE
[Docs] Two links in "Commands, Menus and Keybindings" don't work

### ISSUE THREAD

**Issue by BariekR** [eclipse-theia/theia-website#651]
### Description:
There are two hyperlinks at [https://theia-ide.org/docs/commands_keybindings/](https://theia-ide.org/docs/commands_keybindings/) that don't work (Page not found):
- "TypeDoc for the CommandRegistry",
- "Key documentation".

**Comment by BariekR** [comment]
"the typedoc" at [https://theia-ide.org/docs/widgets/](https://theia-ide.org/docs/widgets/) as well.

**Comment by JonasHelming** [comment]
https://github.com/eclipse-theia/theia/pull/13822
